# Generated by Django 5.1.1 on 2024-09-26 10:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default=datetime.datetime(2024, 9, 26, 10, 5, 42, 614517, tzinfo=datetime.timezone.utc))),
                ('category', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='task.category')),
            ],
        ),
    ]
