# Generated by Django 5.1.1 on 2024-09-27 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='created',
            field=models.DateField(default=datetime.datetime(2024, 9, 27, 13, 48, 28, 166607, tzinfo=datetime.timezone.utc)),
        ),
    ]
